{% set version = "0.3.6.2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-prediction
  version: {{ version|replace("-", "_") }}

source:
  fn: prediction_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/prediction_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/prediction/prediction_{{ version }}.tar.gz
  sha256: c537c33420bb0af60f85e448139ebee7a077dd262fc6309f81881929eaeaa74f

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
  host:
    - r-base
    - r-data.table
  run:
    - r-base
    - r-data.table

test:
  commands:
    - $R -e "library('prediction')"           # [not win]
    - "\"%R%\" -e \"library('prediction')\""  # [win]

about:
  home: https://github.com/leeper/prediction
  license: MIT
  summary: A one-function package containing 'prediction()', a type-safe alternative to 'predict()'
    that always returns a data frame. The package currently supports common model types
    (e.g., "lm", "glm") from the 'stats' package, as well as numerous other model classes
    from other add-on packages. See the README or main package documentation page for
    a complete listing.
  license_family: MIT

extra:
  recipe-maintainers:
    - ccwang002
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
