{% set version = '0.3.6.2' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-prediction
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/prediction_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/prediction/prediction_{{ version }}.tar.gz
  sha256: c537c33420bb0af60f85e448139ebee7a077dd262fc6309f81881929eaeaa74f

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-data.table
  run:
    - r-base
    - r-data.table

test:
  commands:
    - $R -e "library('prediction')"           # [not win]
    - "\"%R%\" -e \"library('prediction')\""  # [win]

about:
  home: https://github.com/leeper/prediction
  license: MIT
  summary: A one-function package containing 'prediction()', a type-safe alternative to 'predict()'
    that always returns a data frame. The package currently supports common model types
    (e.g., "lm", "glm") from the 'stats' package, as well as numerous other model classes
    from other add-on packages. See the README or main package documentation page for
    a complete listing.
  license_family: MIT

extra:
  recipe-maintainers:
    - conda-forge/r
    - ccwang002

# Package: prediction
# Type: Package
# Title: Tidy, Type-Safe 'prediction()' Methods
# Description: A one-function package containing 'prediction()', a type-safe alternative to 'predict()' that always returns a data frame. The package currently supports common model types (e.g., "lm", "glm") from the 'stats' package, as well as numerous other model classes from other add-on packages. See the README or main package documentation page for a complete listing.
# License: MIT + file LICENSE
# Version: 0.3.6.2
# Date: 2019-01-31
# Authors@R: c(person("Thomas J.", "Leeper", role = c("aut", "cre"),  email = "thosjleeper@gmail.com", comment = c(ORCID = "0000-0003-4097-6326")), person("Carl", "Ganz", role = "ctb", email = "carlganz@ucla.edu") )
# URL: https://github.com/leeper/prediction
# BugReports: https://github.com/leeper/prediction/issues
# Imports: utils, stats, data.table
# Suggests: datasets, methods, testthat
# Enhances: AER, aod, betareg, biglm, brglm, caret, crch, e1071, earth, ff, ffbase, gam (>= 1.15), gee, glmnet, glmx, kernlab, lme4, MASS, mclogit, mda, mlogit, MNP, nlme, nnet, ordinal, plm, pscl, quantreg, rpart, sampleSelection, speedglm, survey (>= 3.31-5), survival, truncreg, VGAM
# ByteCompile: true
# RoxygenNote: 6.1.1
# NeedsCompilation: no
# Packaged: 2019-01-31 11:12:44 UTC; THOMAS
# Author: Thomas J. Leeper [aut, cre] (<https://orcid.org/0000-0003-4097-6326>), Carl Ganz [ctb]
# Maintainer: Thomas J. Leeper <thosjleeper@gmail.com>
# Repository: CRAN
# Date/Publication: 2019-01-31 15:30:03 UTC
